version: '3.7'

services:
  postgresql-server:
    image: postgres:latest
    container_name: postgresql-server
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:latest
    container_name: zabbix-server
    restart: unless-stopped
    depends_on:
      - postgresql-server
    environment:
      DB_SERVER_HOST: postgresql-server
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "10051:10051"
    volumes:
      - zabbix-server-data:/var/lib/zabbix
      - zabbix-snmptraps-data:/var/lib/zabbix/snmptraps
      - zabbix-export-data:/var/lib/zabbix/export

  zabbix-web-nginx-pgsql:
    image: zabbix/zabbix-web-nginx-pgsql:latest
    container_name: zabbix-web
    restart: unless-stopped
    depends_on:
      - postgresql-server
      - zabbix-server
    environment:
      DB_SERVER_HOST: postgresql-server
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: ${PHP_TZ}
    ports:
      - "${ZABBIX_FRONTEND_PORT}:7788"
    volumes:
      - zabbix-web-data:/usr/share/zabbix

  zabbix-agent:
    image: zabbix/zabbix-agent:latest
    container_name: zabbix-agent
    restart: unless-stopped
    depends_on:
      - zabbix-server
    environment:
      ZBX_HOSTNAME: "zabbix-server"
      ZBX_SERVER_HOST: zabbix-server
      ZBX_SERVER_PORT: '10051'
      ZBX_SERVER_ACTIVE: zabbix-server

  # db:
  #     container_name: kiwi_db
  #     image: mariadb:latest
  #     command:
  #         --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  #     volumes:
  #         - db_data:/var/lib/mysql
  #     restart: always
  #     environment:
  #         # checkov:skip=CKV_SECRET_6:Base64 High Entropy String
  #         MYSQL_ROOT_PASSWORD: kiwi-1s-aw3s0m3
  #         MYSQL_DATABASE: kiwi
  #         MYSQL_USER: kiwi
  #         MYSQL_PASSWORD: kiwi

  # web:
  #     container_name: kiwi_web
  #     depends_on:
  #         - db
  #     restart: always
  #     image: pub.kiwitcms.eu/kiwitcms/kiwi:latest
  #     ports:
  #         - 81:8080
  #         - 443:8443
  #     volumes:
  #         - uploads:/Kiwi/uploads:Z
  #     environment:
  #         KIWI_DB_HOST: db
  #         KIWI_DB_PORT: 3306
  #         KIWI_DB_NAME: kiwi
  #         KIWI_DB_USER: kiwi
  #         KIWI_DB_PASSWORD: kiwi
  #     cap_drop:
  #       - ALL



volumes:
  postgresql-data:
  zabbix-server-data:
  zabbix-snmptraps-data:
  zabbix-export-data:
  zabbix-web-data:
  # db_data:
  # uploads: